apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-api-basic
  namespace: grade-demo
  labels:
    app: grade-api-basic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grade-api-basic
  template:
    metadata:
      labels:
        app: grade-api-basic
    spec:
      containers:
      - name: grade-api-basic
        image: rslim087/kubernetes-course-grade-submission-api:stateless
        ###image: harbor.nghiapg.net/grade-api/grade-api:1.0.0
        ports:
          - containerPort: 3000
