### It seems that ArgoCD is not relizing anything related to Ingress resources (both ArgoCD itself, and its applications, so we bypass this file, and use svc Loadbancer directly instead
### We will investigate the Ingress for ArgoCD later !!!

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: grade-demo
  name: grade-api-basic
  labels:
    name: grade-api-basic
spec:
  rules:
  - host: gradeportal.nghiapg.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: grade-api-basic
            port: 
              number: 3000
  ingressClassName: nginx ### We use nginx ingress (a shared Public LoadBalancer) to expose ClusterIP svc of grade-api_service to public to do the test
